local Constant = {
    DEFAULT_BAR_HEIGHT = 32,
    DEFAULT_ELEMENT_HEIGHT = 32,
    ELEMENT_MIN_WIDTH = 32,
    SCROLL_BAR_WIDTH = 16,

    DEFAULT_FONT_SIZE = 24,
    BTN_SIDE_OFFSET = 8,
    TAB_VIEW_SIDE_OFFSET = 4,
    DRAG_AREA_SIZE = 8,
}

return Constant