---@API

---@class Keys_Value 描述一个键盘键值。
local Keys_Value = {}

---@class Keys 键盘键值枚举类。
---@field None Keys_Value 预留。
---@field Back Keys_Value BACKSPACE。
---@field Tab Keys_Value
---@field Enter Keys_Value ECS。
---@field CapsLock Keys_Value
---@field Escape Keys_Value
---@field Space Keys_Value
---@field PageUp Keys_Value
---@field PageDown Keys_Value
---@field End Keys_Value
---@field Home Keys_Value
---@field Left Keys_Value
---@field Up Keys_Value
---@field Right Keys_Value
---@field Down Keys_Value
---@field Select Keys_Value
---@field Print Keys_Value
---@field Execute Keys_Value
---@field PrintScreen Keys_Value
---@field Insert Keys_Value
---@field Delete Keys_Value
---@field Help Keys_Value
---@field D0 Keys_Value
---@field D1 Keys_Value
---@field D2 Keys_Value
---@field D3 Keys_Value
---@field D4 Keys_Value
---@field D5 Keys_Value
---@field D6 Keys_Value
---@field D7 Keys_Value
---@field D8 Keys_Value
---@field D9 Keys_Value
---@field A Keys_Value
---@field B Keys_Value
---@field C Keys_Value
---@field D Keys_Value
---@field E Keys_Value
---@field F Keys_Value
---@field G Keys_Value
---@field H Keys_Value
---@field I Keys_Value
---@field J Keys_Value
---@field K Keys_Value
---@field L Keys_Value
---@field M Keys_Value
---@field N Keys_Value
---@field O Keys_Value
---@field P Keys_Value
---@field Q Keys_Value
---@field R Keys_Value
---@field S Keys_Value
---@field T Keys_Value
---@field U Keys_Value
---@field V Keys_Value
---@field W Keys_Value
---@field X Keys_Value
---@field Y Keys_Value
---@field Z Keys_Value
---@field LeftWindows Keys_Value
---@field RightWindows Keys_Value
---@field Apps Keys_Value
---@field Sleep Keys_Value
---@field NumPad0 Keys_Value 数字按键0。
---@field NumPad1 Keys_Value 数字按键1。
---@field NumPad2 Keys_Value 数字按键2。
---@field NumPad3 Keys_Value 数字按键3。
---@field NumPad4 Keys_Value 数字按键4。
---@field NumPad5 Keys_Value 数字按键5。
---@field NumPad6 Keys_Value 数字按键6。
---@field NumPad7 Keys_Value 数字按键7。
---@field NumPad8 Keys_Value 数字按键8。
---@field NumPad9 Keys_Value 数字按键9。
---@field Multiply Keys_Value
---@field Add Keys_Value
---@field Separator Keys_Value
---@field Subtract Keys_Value
---@field Decimal Keys_Value
---@field Divide Keys_Value
---@field F1 Keys_Value
---@field F2 Keys_Value
---@field F3 Keys_Value
---@field F4 Keys_Value
---@field F5 Keys_Value
---@field F6 Keys_Value
---@field F7 Keys_Value
---@field F8 Keys_Value
---@field F9 Keys_Value
---@field F10 Keys_Value
---@field F11 Keys_Value
---@field F12 Keys_Value
---@field F13 Keys_Value
---@field F14 Keys_Value
---@field F15 Keys_Value
---@field F16 Keys_Value
---@field F17 Keys_Value
---@field F18 Keys_Value
---@field F19 Keys_Value
---@field F20 Keys_Value
---@field F21 Keys_Value
---@field F22 Keys_Value
---@field F23 Keys_Value
---@field F24 Keys_Value
---@field NumLock Keys_Value
---@field Scroll Keys_Value
---@field LeftShift Keys_Value
---@field RightShift Keys_Value
---@field LeftControl Keys_Value
---@field RightControl Keys_Value
---@field LeftAlt Keys_Value
---@field RightAlt Keys_Value
---@field BrowserBack Keys_Value
---@field BrowserForward Keys_Value
---@field BrowserRefresh Keys_Value
---@field BrowserStop Keys_Value
---@field BrowserSearch Keys_Value
---@field BrowserFavorites Keys_Value
---@field BrowserHome Keys_Value
---@field VolumeMute Keys_Value
---@field VolumeDown Keys_Value
---@field VolumeUp Keys_Value
---@field MediaNextTrack Keys_Value
---@field MediaPreviousTrack Keys_Value
---@field MediaStop Keys_Value
---@field MediaPlayPause Keys_Value Play/Pause Media.
---@field LaunchMail Keys_Value Start Mail.
---@field SelectMedia Keys_Value
---@field LaunchApplication1 Keys_Value Start Application 1.
---@field LaunchApplication2 Keys_Value Start Application 2.
---@field OemSemicolon Keys_Value The OEM Semicolon key on a US standard keyboard.
---@field OemPlus Keys_Value For any country/region, the '+'.
---@field OemComma Keys_Value For any country/region, the ','.
---@field OemMinus Keys_Value For any country/region, the '-'.
---@field OemPeriod Keys_Value For any country/region, the '.'.
---@field OemQuestion Keys_Value The OEM question mark key on a US standard keyboard.
---@field OemTilde Keys_Value The OEM tilde key on a US standard keyboard.
---@field OemOpenBrackets Keys_Value The OEM open bracket key on a US standard keyboard.
---@field OemPipe Keys_Value The OEM pipe key on a US standard keyboard.
---@field OemCloseBrackets Keys_Value The OEM close bracket key on a US standard keyboard.
---@field OemQuotes Keys_Value The OEM singled/double quote key on a US standard keyboard.
---@field Oem8 Keys_Value Used for miscellaneous characters; it can vary by keyboard.
---@field OemBackslash Keys_Value The OEM angle bracket or backslash key on the RT 102 key keyboard.
---@field ProcessKey Keys_Value IME PROCESS.
---@field Attn Keys_Value
---@field Crsel Keys_Value CrSel.
---@field Exsel Keys_Value ExSel.
---@field EraseEof Keys_Value Erase EOF.
---@field Play Keys_Value
---@field Zoom Keys_Value
---@field Pa1 Keys_Value
---@field OemClear Keys_Value
---@field ChatPadGreen Keys_Value Green ChatPad.
---@field ChatPadOrange Keys_Value Orange ChatPad.
---@field Pause Keys_Value
---@field ImeConvert Keys_Value IME Convert.
---@field ImeNoConvert Keys_Value IME NoConvert.
---@field Kana Keys_Value Kana key on Japanese keyboards.
---@field Kanji Keys_Value Kanji key on Japanese keyboards.
---@field OemAuto Keys_Value OEM Auto.
---@field OemCopy Keys_Value OEM Copy.
---@field OemEnlW Keys_Value OEM Enlarge Window.
local Keys = {}

return Keys